[package]
name = "brightness"
version = "0.4.1"
authors = ["Stephane Raux <stephaneyfx@gmail.com>", "Contributors"]
edition = "2018"
description = "Get and set display brightness"
license = "0BSD"
homepage = "https://github.com/stephaneyfx/brightness"
repository = "https://github.com/stephaneyfx/brightness.git"
documentation = "https://docs.rs/brightness"
keywords = ["brightness", "backlight"]

[dependencies]
async-trait = "0.1.50"
futures = "0.3.16"
thiserror = "1.0.26"

[target.'cfg(target_os = "linux")'.dependencies]
zbus = "1.9.1"

[target.'cfg(windows)'.dependencies.windows]
version = "0.29.0"
features = [
    "std",
    "Win32_Foundation",
    "Win32_Devices_Display",
    "Win32_Graphics_Gdi",
    "Win32_Storage_FileSystem",
    "Win32_Security",
    "Win32_System_IO",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_SystemServices",
]
